Data file added, and needed corrections made
nas-cam/QA-Internship-Automation pull request #2
Opened 2023-04-04 13:19 UTC by nas-cam

Data needed for testing added in a file. Hardcoded strings removed and implemented different logic for data injection into the test.

2023-04-05 13:40 UTC, ElvedinS96 requested changes

2023-04-05 13:40 UTC, ElvedinS96 commented on internship-automation/pageobjects/myAccountPage.js
> +        await this.inputPassword.setValue(password);
Function name says enterPassword, but here you are clicking also. It probably means there should be another clickOnPasswordInput() :)

2023-04-05 13:40 UTC, ElvedinS96 commented on internship-automation/test-suites/smokeTest/smoke-test.js
>          await expect(securePage.flashAlert).toHaveTextContaining("MY ACCOUNT");
"MY ACCOUNT" is data also, and all others where you check toHaveTextContaining().

2023-04-05 14:33 UTC, nas-cam commented on internship-automation/pageobjects/myAccountPage.js
> +        await this.inputPassword.setValue(password);
Yes, I forgot about SRP, I will correct this.

2023-04-06 08:48 UTC, ElvedinS96 requested changes

2023-04-06 08:48 UTC, ElvedinS96 commented on internship-automation/pageobjects/productPage.js
> +
Extra space?

2023-04-06 08:48 UTC, ElvedinS96 commented on internship-automation/data/commonData.js
> +};
Missing space at the end?

2023-04-06 08:48 UTC, ElvedinS96 commented on internship-automation/data/commonData.js
> +
Can you add spaces in between these sections, like here?

2023-04-06 08:48 UTC, ElvedinS96 commented on internship-automation/test-suites/smokeTest/smoke-test.js
> +
Extra space?

2023-04-06 09:08 UTC, ElvedinS96 approved these changes
This is some great work, well done 👏

2023-04-06 09:20 UTC, merged